#include "u64_compressed_seq.h"
#include <stdlib.h>
struct U64CompressedSeq{size_t size,block_size,block_count,byte_count;uint64_t*bases;size_t*offsets;uint8_t*bytes;};
static size_t varint_size(uint64_t x){size_t n=1;while(x>=128U){x>>=7;++n;}return n;}
static void write_varint(uint64_t x,uint8_t*out,size_t*pos){while(x>=128U){out[(*pos)++]=(uint8_t)((x&UINT64_C(0x7f))|UINT64_C(0x80));x>>=7;}out[(*pos)++]=(uint8_t)x;}
static bool read_varint(const uint8_t*data,size_t end,size_t*pos,uint64_t*out){uint64_t v=0;unsigned shift=0;for(unsigned i=0;i<10;++i){if(*pos>=end)return false;uint8_t b=data[(*pos)++];if(i==9&&(b&0xFEU)!=0)return false;v|=(uint64_t)(b&0x7fU)<<shift;if((b&0x80U)==0){*out=v;return true;}shift+=7;}return false;}
U64CompressedSeq*u64_compressed_seq_create(const uint64_t*values,size_t count,size_t block_size){if(block_size==0||(count>0&&!values))return NULL;for(size_t i=1;i<count;++i)if(values[i-1]>=values[i])return NULL;U64CompressedSeq*s=calloc(1,sizeof*s);if(!s)return NULL;s->size=count;s->block_size=block_size;if(count==0){s->offsets=calloc(1,sizeof(size_t));if(!s->offsets){free(s);return NULL;}return s;}if(count>SIZE_MAX-(block_size-1)){free(s);return NULL;}s->block_count=(count+block_size-1)/block_size;if(s->block_count>SIZE_MAX/sizeof(uint64_t)||s->block_count==SIZE_MAX||(s->block_count+1)>SIZE_MAX/sizeof(size_t)){free(s);return NULL;}s->bases=malloc(s->block_count*sizeof*s->bases);s->offsets=calloc(s->block_count+1,sizeof*s->offsets);if(!s->bases||!s->offsets){u64_compressed_seq_free(s);return NULL;}size_t need=0;for(size_t b=0;b<s->block_count;++b){size_t start=b*block_size,end=start+block_size;if(end>count)end=count;s->bases[b]=values[start];for(size_t i=start+1;i<end;++i){uint64_t gap=values[i]-values[i-1];size_t z=varint_size(gap);if(SIZE_MAX-need<z){u64_compressed_seq_free(s);return NULL;}need+=z;}}s->byte_count=need;if(need){s->bytes=malloc(need);if(!s->bytes){u64_compressed_seq_free(s);return NULL;}}size_t pos=0;for(size_t b=0;b<s->block_count;++b){s->offsets[b]=pos;size_t start=b*block_size,end=start+block_size;if(end>count)end=count;for(size_t i=start+1;i<end;++i)write_varint(values[i]-values[i-1],s->bytes,&pos);}s->offsets[s->block_count]=pos;return s;}
void u64_compressed_seq_free(U64CompressedSeq*s){if(!s)return;free(s->bases);free(s->offsets);free(s->bytes);free(s);}
size_t u64_compressed_seq_size(const U64CompressedSeq*s){return s?s->size:0;}size_t u64_compressed_seq_block_size(const U64CompressedSeq*s){return s?s->block_size:0;}size_t u64_compressed_seq_block_count(const U64CompressedSeq*s){return s?s->block_count:0;}size_t u64_compressed_seq_encoded_bytes(const U64CompressedSeq*s){return s?s->byte_count:0;}
bool u64_compressed_seq_get(const U64CompressedSeq*s,size_t idx,uint64_t*out){if(!s||!out||idx>=s->size)return false;size_t b=idx/s->block_size,within=idx%s->block_size;uint64_t v=s->bases[b];size_t pos=s->offsets[b],end=s->offsets[b+1];for(size_t i=0;i<within;++i){uint64_t gap=0;if(!read_varint(s->bytes,end,&pos,&gap)||gap==0||UINT64_MAX-v<gap)return false;v+=gap;}*out=v;return true;}
size_t u64_compressed_seq_lower_bound(const U64CompressedSeq*s,uint64_t target){if(!s||s->size==0)return 0;size_t lo=0,hi=s->block_count;while(lo<hi){size_t m=lo+(hi-lo)/2;if(s->bases[m]<=target)lo=m+1;else hi=m;}if(lo==0)return 0;size_t b=lo-1,start=b*s->block_size,end_index=start+s->block_size;if(end_index>s->size)end_index=s->size;uint64_t v=s->bases[b];if(v>=target)return start;size_t pos=s->offsets[b],end=s->offsets[b+1];for(size_t i=start+1;i<end_index;++i){uint64_t gap=0;if(!read_varint(s->bytes,end,&pos,&gap)||gap==0||UINT64_MAX-v<gap)return s->size;v+=gap;if(v>=target)return i;}return end_index;}
bool u64_compressed_seq_validate(const U64CompressedSeq*s){if(!s||s->block_size==0||!s->offsets)return false;if(s->size==0)return s->block_count==0&&s->byte_count==0&&s->bases==NULL&&s->bytes==NULL&&s->offsets[0]==0;if(!s->bases)return false;if(s->byte_count>0&&!s->bytes)return false;if(s->size>SIZE_MAX-(s->block_size-1))return false;size_t expected=(s->size+s->block_size-1)/s->block_size;if(s->block_count!=expected||s->offsets[0]!=0||s->offsets[s->block_count]!=s->byte_count)return false;uint64_t previous=0;bool have_previous=false;for(size_t b=0;b<s->block_count;++b){if(s->offsets[b]>s->offsets[b+1]||s->offsets[b+1]>s->byte_count)return false;size_t start=b*s->block_size,end_index=start+s->block_size;if(end_index>s->size)end_index=s->size;uint64_t v=s->bases[b];if(have_previous&&v<=previous)return false;size_t pos=s->offsets[b],end=s->offsets[b+1];for(size_t i=start+1;i<end_index;++i){uint64_t gap=0;if(!read_varint(s->bytes,end,&pos,&gap)||gap==0||UINT64_MAX-v<gap)return false;v+=gap;}if(pos!=end)return false;previous=v;have_previous=true;}return true;}
