#include "sparse_matrix.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
typedef struct{size_t row,col;double value;}Entry;
struct CooMatrix{size_t rows,cols,count,capacity;Entry*entries;};
struct CsrMatrix{size_t rows,cols,nnz;size_t*row_ptr,*col_idx;double*values;};
struct CscMatrix{size_t rows,cols,nnz;size_t*col_ptr,*row_idx;double*values;};
CooMatrix*coo_matrix_create(size_t r,size_t c){if(r==0||c==0)return NULL;CooMatrix*m=calloc(1,sizeof*m);if(!m)return NULL;m->rows=r;m->cols=c;return m;}
void coo_matrix_free(CooMatrix*m){if(!m)return;free(m->entries);free(m);}
size_t coo_matrix_nnz(const CooMatrix*m){return m?m->count:0;}
static bool reserve_entries(CooMatrix*m,size_t need){if(need<=m->capacity)return true;size_t c=m->capacity?m->capacity*2:16;if(c<need)c=need;if(c>SIZE_MAX/sizeof(Entry))return false;Entry*p=realloc(m->entries,c*sizeof*p);if(!p)return false;m->entries=p;m->capacity=c;return true;}
bool coo_matrix_add(CooMatrix*m,size_t r,size_t c,double v){if(!m||r>=m->rows||c>=m->cols)return false;if(v==0.0)return true;if(m->count==SIZE_MAX||!reserve_entries(m,m->count+1))return false;m->entries[m->count++]=(Entry){r,c,v};return true;}
bool coo_matrix_validate(const CooMatrix*m){if(!m||m->rows==0||m->cols==0||m->count>m->capacity||(m->capacity&&!m->entries))return false;for(size_t i=0;i<m->count;++i)if(m->entries[i].row>=m->rows||m->entries[i].col>=m->cols||m->entries[i].value==0.0)return false;return true;}
static int cmp_rc(const void*a,const void*b){const Entry*x=a,*y=b;if(x->row<y->row)return-1;if(x->row>y->row)return 1;return x->col<y->col?-1:(x->col>y->col?1:0);}
static int cmp_cr(const void*a,const void*b){const Entry*x=a,*y=b;if(x->col<y->col)return-1;if(x->col>y->col)return 1;return x->row<y->row?-1:(x->row>y->row?1:0);}
static Entry*canonical_entries(const CooMatrix*m,bool by_row,size_t*out_n){*out_n=0;if(m->count==0)return NULL;if(m->count>SIZE_MAX/sizeof(Entry))return NULL;Entry*tmp=malloc(m->count*sizeof*tmp);if(!tmp)return NULL;memcpy(tmp,m->entries,m->count*sizeof*tmp);qsort(tmp,m->count,sizeof*tmp,by_row?cmp_rc:cmp_cr);size_t n=0;for(size_t i=0;i<m->count;){Entry e=tmp[i++];while(i<m->count&&tmp[i].row==e.row&&tmp[i].col==e.col){e.value+=tmp[i].value;++i;}if(e.value!=0.0)tmp[n++]=e;}*out_n=n;return tmp;}
CsrMatrix*coo_matrix_to_csr(const CooMatrix*m){if(!coo_matrix_validate(m))return NULL;size_t n=0;Entry*e=canonical_entries(m,true,&n);if(m->count&& !e)return NULL;if(m->rows==SIZE_MAX||m->rows+1>SIZE_MAX/sizeof(size_t)||n>SIZE_MAX/sizeof(size_t)||n>SIZE_MAX/sizeof(double)){free(e);return NULL;}CsrMatrix*r=calloc(1,sizeof*r);if(!r){free(e);return NULL;}r->rows=m->rows;r->cols=m->cols;r->nnz=n;r->row_ptr=calloc(m->rows+1,sizeof* r->row_ptr);if(!r->row_ptr){free(e);csr_matrix_free(r);return NULL;}if(n){r->col_idx=malloc(n*sizeof*r->col_idx);r->values=malloc(n*sizeof*r->values);if(!r->col_idx||!r->values){free(e);csr_matrix_free(r);return NULL;}}for(size_t i=0;i<n;++i)++r->row_ptr[e[i].row+1];for(size_t i=1;i<=m->rows;++i)r->row_ptr[i]+=r->row_ptr[i-1];for(size_t i=0;i<n;++i){r->col_idx[i]=e[i].col;r->values[i]=e[i].value;}free(e);return r;}
CscMatrix*coo_matrix_to_csc(const CooMatrix*m){if(!coo_matrix_validate(m))return NULL;size_t n=0;Entry*e=canonical_entries(m,false,&n);if(m->count&& !e)return NULL;if(m->cols==SIZE_MAX||m->cols+1>SIZE_MAX/sizeof(size_t)||n>SIZE_MAX/sizeof(size_t)||n>SIZE_MAX/sizeof(double)){free(e);return NULL;}CscMatrix*r=calloc(1,sizeof*r);if(!r){free(e);return NULL;}r->rows=m->rows;r->cols=m->cols;r->nnz=n;r->col_ptr=calloc(m->cols+1,sizeof*r->col_ptr);if(!r->col_ptr){free(e);csc_matrix_free(r);return NULL;}if(n){r->row_idx=malloc(n*sizeof*r->row_idx);r->values=malloc(n*sizeof*r->values);if(!r->row_idx||!r->values){free(e);csc_matrix_free(r);return NULL;}}for(size_t i=0;i<n;++i)++r->col_ptr[e[i].col+1];for(size_t i=1;i<=m->cols;++i)r->col_ptr[i]+=r->col_ptr[i-1];for(size_t i=0;i<n;++i){r->row_idx[i]=e[i].row;r->values[i]=e[i].value;}free(e);return r;}
void csr_matrix_free(CsrMatrix*m){if(!m)return;free(m->row_ptr);free(m->col_idx);free(m->values);free(m);}
void csc_matrix_free(CscMatrix*m){if(!m)return;free(m->col_ptr);free(m->row_idx);free(m->values);free(m);}
size_t csr_matrix_rows(const CsrMatrix*m){return m?m->rows:0;}size_t csr_matrix_cols(const CsrMatrix*m){return m?m->cols:0;}size_t csr_matrix_nnz(const CsrMatrix*m){return m?m->nnz:0;}
size_t csc_matrix_rows(const CscMatrix*m){return m?m->rows:0;}size_t csc_matrix_cols(const CscMatrix*m){return m?m->cols:0;}size_t csc_matrix_nnz(const CscMatrix*m){return m?m->nnz:0;}
bool csr_matrix_get(const CsrMatrix*m,size_t r,size_t c,double*out){if(!m||!out||r>=m->rows||c>=m->cols)return false;size_t lo=m->row_ptr[r],hi=m->row_ptr[r+1];while(lo<hi){size_t mid=lo+(hi-lo)/2;if(m->col_idx[mid]<c)lo=mid+1;else hi=mid;}*out=(lo<m->row_ptr[r+1]&&m->col_idx[lo]==c)?m->values[lo]:0.0;return true;}
bool csc_matrix_get(const CscMatrix*m,size_t r,size_t c,double*out){if(!m||!out||r>=m->rows||c>=m->cols)return false;size_t lo=m->col_ptr[c],hi=m->col_ptr[c+1];while(lo<hi){size_t mid=lo+(hi-lo)/2;if(m->row_idx[mid]<r)lo=mid+1;else hi=mid;}*out=(lo<m->col_ptr[c+1]&&m->row_idx[lo]==r)?m->values[lo]:0.0;return true;}
bool csr_matrix_spmv(const CsrMatrix*m,const double*x,size_t xl,double*y,size_t yl){if(!m||!x||!y||xl!=m->cols||yl!=m->rows)return false;for(size_t r=0;r<m->rows;++r){double sum=0.0;for(size_t i=m->row_ptr[r];i<m->row_ptr[r+1];++i)sum+=m->values[i]*x[m->col_idx[i]];y[r]=sum;}return true;}
bool csr_matrix_validate(const CsrMatrix*m){if(!m||m->rows==0||m->cols==0||!m->row_ptr)return false;if(m->nnz&&(!m->col_idx||!m->values))return false;if(m->row_ptr[0]!=0||m->row_ptr[m->rows]!=m->nnz)return false;for(size_t r=0;r<m->rows;++r){if(m->row_ptr[r]>m->row_ptr[r+1]||m->row_ptr[r+1]>m->nnz)return false;for(size_t i=m->row_ptr[r];i<m->row_ptr[r+1];++i){if(m->col_idx[i]>=m->cols||m->values[i]==0.0)return false;if(i>m->row_ptr[r]&&m->col_idx[i-1]>=m->col_idx[i])return false;}}return true;}
bool csc_matrix_validate(const CscMatrix*m){if(!m||m->rows==0||m->cols==0||!m->col_ptr)return false;if(m->nnz&&(!m->row_idx||!m->values))return false;if(m->col_ptr[0]!=0||m->col_ptr[m->cols]!=m->nnz)return false;for(size_t c=0;c<m->cols;++c){if(m->col_ptr[c]>m->col_ptr[c+1]||m->col_ptr[c+1]>m->nnz)return false;for(size_t i=m->col_ptr[c];i<m->col_ptr[c+1];++i){if(m->row_idx[i]>=m->rows||m->values[i]==0.0)return false;if(i>m->col_ptr[c]&&m->row_idx[i-1]>=m->row_idx[i])return false;}}return true;}
