#include "inverted_index.h"
#include <stdint.h>
#include <stdlib.h>
#include <string.h>
typedef struct TermEntry{char*term;uint64_t*docs;size_t doc_count,doc_capacity;struct TermEntry*next;}TermEntry;
struct InvertedIndex{TermEntry**buckets;size_t bucket_count,term_count;};
static uint64_t hash_term(const char*s){uint64_t h=UINT64_C(1469598103934665603);for(;*s;++s){h^=(unsigned char)*s;h*=UINT64_C(1099511628211);}return h;}
static bool ascii_alnum(unsigned char c){return(c>='a'&&c<='z')||(c>='A'&&c<='Z')||(c>='0'&&c<='9');}
static char ascii_lower(unsigned char c){return(c>='A'&&c<='Z')?(char)(c-'A'+'a'):(char)c;}
InvertedIndex*inverted_index_create(size_t n){if(n==0||n>SIZE_MAX/sizeof(TermEntry*))return NULL;InvertedIndex*x=calloc(1,sizeof*x);if(!x)return NULL;x->buckets=calloc(n,sizeof*x->buckets);if(!x->buckets){free(x);return NULL;}x->bucket_count=n;return x;}
static void free_entry(TermEntry*e){if(!e)return;free(e->term);free(e->docs);free(e);}
void inverted_index_free(InvertedIndex*x){if(!x)return;for(size_t i=0;i<x->bucket_count;++i){TermEntry*e=x->buckets[i];while(e){TermEntry*n=e->next;free_entry(e);e=n;}}free(x->buckets);free(x);}
size_t inverted_index_term_count(const InvertedIndex*x){return x?x->term_count:0;}
static TermEntry*find_entry(const InvertedIndex*x,const char*term){if(!x||!term||!*term)return NULL;size_t b=(size_t)(hash_term(term)%x->bucket_count);for(TermEntry*e=x->buckets[b];e;e=e->next)if(strcmp(e->term,term)==0)return e;return NULL;}
static size_t lower_doc(const TermEntry*e,uint64_t d){size_t l=0,h=e->doc_count;while(l<h){size_t m=l+(h-l)/2;if(e->docs[m]<d)l=m+1;else h=m;}return l;}
static bool reserve_docs(TermEntry*e,size_t need){if(need<=e->doc_capacity)return true;size_t c=e->doc_capacity?e->doc_capacity*2:4;if(c<need)c=need;if(c>SIZE_MAX/sizeof(uint64_t))return false;uint64_t*p=realloc(e->docs,c*sizeof*p);if(!p)return false;e->docs=p;e->doc_capacity=c;return true;}
static bool rehash(InvertedIndex*x,size_t n){if(n==0||n>SIZE_MAX/sizeof(TermEntry*))return false;TermEntry**b=calloc(n,sizeof*b);if(!b)return false;for(size_t i=0;i<x->bucket_count;++i){TermEntry*e=x->buckets[i];while(e){TermEntry*next=e->next;size_t j=(size_t)(hash_term(e->term)%n);e->next=b[j];b[j]=e;e=next;}}free(x->buckets);x->buckets=b;x->bucket_count=n;return true;}
static bool add_term_doc(InvertedIndex*x,const char*term,uint64_t doc){TermEntry*e=find_entry(x,term);if(!e){if(x->term_count==SIZE_MAX)return false;const size_t grow_threshold=x->bucket_count-x->bucket_count/4;if(x->term_count>=grow_threshold){if(x->bucket_count>SIZE_MAX/2)return false;if(!rehash(x,x->bucket_count*2))return false;}size_t len=strlen(term);e=calloc(1,sizeof*e);if(!e)return false;e->term=malloc(len+1);if(!e->term){free(e);return false;}memcpy(e->term,term,len+1);size_t b=(size_t)(hash_term(term)%x->bucket_count);e->next=x->buckets[b];x->buckets[b]=e;++x->term_count;}size_t i=lower_doc(e,doc);if(i<e->doc_count&&e->docs[i]==doc)return true;if(e->doc_count==SIZE_MAX||!reserve_docs(e,e->doc_count+1))return false;memmove(&e->docs[i+1],&e->docs[i],(e->doc_count-i)*sizeof*e->docs);e->docs[i]=doc;++e->doc_count;return true;}
bool inverted_index_add_document(InvertedIndex*x,uint64_t doc,const char*text){if(!x||!text)return false;size_t n=strlen(text);if(n==SIZE_MAX)return false;char*token=malloc(n+1);if(!token)return false;size_t i=0;while(i<n){while(i<n&&!ascii_alnum((unsigned char)text[i]))++i;if(i==n)break;size_t len=0;while(i<n&&ascii_alnum((unsigned char)text[i]))token[len++]=ascii_lower((unsigned char)text[i++]);token[len]='\0';if(!add_term_doc(x,token,doc)){free(token);return false;}}free(token);return true;}
static bool normalize_term(const char*term,char**out){if(!term||!*term||!out)return false;size_t n=strlen(term);char*s=malloc(n+1);if(!s)return false;for(size_t i=0;i<n;++i){if(!ascii_alnum((unsigned char)term[i])){free(s);return false;}s[i]=ascii_lower((unsigned char)term[i]);}s[n]='\0';*out=s;return true;}
size_t inverted_index_doc_freq(const InvertedIndex*x,const char*term){char*n=NULL;if(!normalize_term(term,&n))return 0;TermEntry*e=find_entry(x,n);free(n);return e?e->doc_count:0;}
bool inverted_index_get_doc(const InvertedIndex*x,const char*term,size_t occ,uint64_t*out){if(!out)return false;char*n=NULL;if(!normalize_term(term,&n))return false;TermEntry*e=find_entry(x,n);free(n);if(!e||occ>=e->doc_count)return false;*out=e->docs[occ];return true;}
size_t inverted_index_and(const InvertedIndex*x,const char*a,const char*b,uint64_t*out,size_t cap){char*na=NULL,*nb=NULL;if(!normalize_term(a,&na)||!normalize_term(b,&nb)){free(na);free(nb);return 0;}TermEntry*ea=find_entry(x,na),*eb=find_entry(x,nb);free(na);free(nb);if(!ea||!eb)return 0;size_t i=0,j=0,count=0;while(i<ea->doc_count&&j<eb->doc_count){if(ea->docs[i]==eb->docs[j]){if(count<cap&&out)out[count]=ea->docs[i];++count;++i;++j;}else if(ea->docs[i]<eb->docs[j])++i;else ++j;}return count;}
bool inverted_index_validate(const InvertedIndex*x){if(!x||!x->buckets||x->bucket_count==0)return false;size_t terms=0;for(size_t b=0;b<x->bucket_count;++b)for(TermEntry*e=x->buckets[b];e;e=e->next){if(!e->term||!*e->term||hash_term(e->term)%x->bucket_count!=b)return false;if(e->doc_count>e->doc_capacity||(e->doc_capacity&&!e->docs))return false;for(const char*p=e->term;*p;++p)if(!((*p>='a'&&*p<='z')||(*p>='0'&&*p<='9')))return false;for(size_t i=1;i<e->doc_count;++i)if(e->docs[i-1]>=e->docs[i])return false;++terms;}return terms==x->term_count;}
