#include "tensor_layout.h"
#include <string.h>
static bool valid_shape(const size_t*shape,size_t ndim){if(!shape||ndim==0||ndim>TENSOR_LAYOUT_MAX_DIMS)return false;for(size_t i=0;i<ndim;++i)if(shape[i]==0)return false;return true;}
bool tensor_layout_row_major(TensorLayout*out,const size_t*shape,size_t ndim){if(!out||!valid_shape(shape,ndim))return false;memset(out,0,sizeof*out);out->ndim=ndim;for(size_t i=0;i<ndim;++i)out->shape[i]=shape[i];size_t s=1;for(size_t i=ndim;i-->0;){out->stride[i]=s;if(shape[i]>SIZE_MAX/s)return false;s*=shape[i];}return true;}
bool tensor_layout_column_major(TensorLayout*out,const size_t*shape,size_t ndim){if(!out||!valid_shape(shape,ndim))return false;memset(out,0,sizeof*out);out->ndim=ndim;for(size_t i=0;i<ndim;++i)out->shape[i]=shape[i];size_t s=1;for(size_t i=0;i<ndim;++i){out->stride[i]=s;if(shape[i]>SIZE_MAX/s)return false;s*=shape[i];}return true;}
bool tensor_layout_offset(const TensorLayout*l,const size_t*idx,size_t*out){if(!l||!idx||!out||!tensor_layout_validate(l))return false;size_t off=l->offset;for(size_t d=0;d<l->ndim;++d){if(idx[d]>=l->shape[d])return false;if(idx[d]&&l->stride[d]>SIZE_MAX/idx[d])return false;size_t add=idx[d]*l->stride[d];if(off>SIZE_MAX-add)return false;off+=add;}*out=off;return true;}
bool tensor_layout_permute(const TensorLayout*s,const size_t*perm,TensorLayout*out){if(!s||!perm||!out||!tensor_layout_validate(s))return false;bool seen[TENSOR_LAYOUT_MAX_DIMS]={0};TensorLayout t={0};t.ndim=s->ndim;t.offset=s->offset;for(size_t i=0;i<s->ndim;++i){if(perm[i]>=s->ndim||seen[perm[i]])return false;seen[perm[i]]=true;t.shape[i]=s->shape[perm[i]];t.stride[i]=s->stride[perm[i]];}*out=t;return true;}
bool tensor_layout_slice(const TensorLayout*s,size_t dim,size_t start,size_t length,size_t step,TensorLayout*out){if(!s||!out||!tensor_layout_validate(s)||dim>=s->ndim||length==0||step==0||start>=s->shape[dim])return false;if(length-1>(SIZE_MAX-start)/step)return false;size_t last=start+(length-1)*step;if(last>=s->shape[dim])return false;if(start&&s->stride[dim]>SIZE_MAX/start)return false;size_t add=start*s->stride[dim];if(s->offset>SIZE_MAX-add)return false;TensorLayout t=*s;t.offset+=add;if(t.stride[dim]>SIZE_MAX/step)return false;t.stride[dim]*=step;t.shape[dim]=length;*out=t;return true;}
bool tensor_layout_is_row_major_contiguous(const TensorLayout*l){if(!tensor_layout_validate(l))return false;size_t s=1;for(size_t i=l->ndim;i-->0;){if(l->stride[i]!=s)return false;if(l->shape[i]>SIZE_MAX/s)return false;s*=l->shape[i];}return true;}
bool tensor_layout_is_column_major_contiguous(const TensorLayout*l){if(!tensor_layout_validate(l))return false;size_t s=1;for(size_t i=0;i<l->ndim;++i){if(l->stride[i]!=s)return false;if(l->shape[i]>SIZE_MAX/s)return false;s*=l->shape[i];}return true;}
bool tensor_layout_validate(const TensorLayout*l){if(!l||l->ndim==0||l->ndim>TENSOR_LAYOUT_MAX_DIMS)return false;for(size_t i=0;i<l->ndim;++i)if(l->shape[i]==0||l->stride[i]==0)return false;return true;}
bool tensor_layout_total_elements(const TensorLayout*l,size_t*out){if(!l||!out||!tensor_layout_validate(l))return false;size_t n=1;for(size_t i=0;i<l->ndim;++i){if(l->shape[i]>SIZE_MAX/n)return false;n*=l->shape[i];}*out=n;return true;}
