#include "piece_table.h"
#include <stdlib.h>
#include <string.h>
typedef enum{SRC_ORIGINAL=0,SRC_ADD=1}PieceSource;
typedef struct{PieceSource source;size_t start,length;}Piece;
struct PieceTable{uint8_t*original;size_t original_size;uint8_t*add;size_t add_size,add_capacity;Piece*pieces;size_t piece_count,size;};
PieceTable*piece_table_create(const uint8_t*orig,size_t len){if(len>0&&!orig)return NULL;PieceTable*t=calloc(1,sizeof*t);if(!t)return NULL;if(len){t->original=malloc(len);if(!t->original){free(t);return NULL;}memcpy(t->original,orig,len);t->pieces=malloc(sizeof* t->pieces);if(!t->pieces){free(t->original);free(t);return NULL;}t->pieces[0]=(Piece){SRC_ORIGINAL,0,len};t->piece_count=1;t->original_size=len;t->size=len;}return t;}
void piece_table_free(PieceTable*t){if(!t)return;free(t->original);free(t->add);free(t->pieces);free(t);}
size_t piece_table_size(const PieceTable*t){return t?t->size:0;}
size_t piece_table_piece_count(const PieceTable*t){return t?t->piece_count:0;}
size_t piece_table_add_buffer_size(const PieceTable*t){return t?t->add_size:0;}
static bool reserve_add(PieceTable*t,size_t need){if(need<=t->add_capacity)return true;size_t c=t->add_capacity?t->add_capacity:16;while(c<need){if(c>SIZE_MAX/2){c=need;break;}c*=2;}uint8_t*p=realloc(t->add,c);if(!p)return false;t->add=p;t->add_capacity=c;return true;}
static bool append_piece(Piece*out,size_t*count,Piece p){if(p.length==0)return true;if(*count>0){Piece*last=&out[*count-1];if(last->source==p.source&&last->start+last->length==p.start){if(SIZE_MAX-last->length<p.length)return false;last->length+=p.length;return true;}}out[(*count)++]=p;return true;}
bool piece_table_insert(PieceTable*t,size_t pos,const uint8_t*bytes,size_t len){if(!t||(len>0&&!bytes)||pos>t->size)return false;if(len==0)return true;if(SIZE_MAX-t->size<len||SIZE_MAX-t->add_size<len)return false;if(t->piece_count>SIZE_MAX-2)return false;Piece*next=malloc((t->piece_count+2)*sizeof*next);if(!next)return false;if(!reserve_add(t,t->add_size+len)){free(next);return false;}size_t out=0,logical=0;bool inserted=false;const size_t add_start=t->add_size;for(size_t i=0;i<t->piece_count;++i){Piece p=t->pieces[i];if(!inserted&&pos>=logical&&pos<=logical+p.length){size_t off=pos-logical;if(off&&!append_piece(next,&out,(Piece){p.source,p.start,off})){free(next);return false;}if(!append_piece(next,&out,(Piece){SRC_ADD,add_start,len})){free(next);return false;}if(off<p.length&&!append_piece(next,&out,(Piece){p.source,p.start+off,p.length-off})){free(next);return false;}inserted=true;}else{if(!append_piece(next,&out,p)){free(next);return false;}}logical+=p.length;}if(!inserted){if(pos!=t->size||!append_piece(next,&out,(Piece){SRC_ADD,add_start,len})){free(next);return false;}}memcpy(t->add+t->add_size,bytes,len);t->add_size+=len;free(t->pieces);t->pieces=next;t->piece_count=out;t->size+=len;return true;}
bool piece_table_erase(PieceTable*t,size_t pos,size_t len){if(!t)return false;if(pos>t->size||len>t->size-pos)return false;if(len==0)return true;Piece*next=malloc((t->piece_count?t->piece_count:1)*sizeof*next);if(!next)return false;const size_t end=pos+len;size_t out=0,logical=0;for(size_t i=0;i<t->piece_count;++i){Piece p=t->pieces[i];size_t ps=logical,pe=logical+p.length;if(pe<=pos||ps>=end){if(!append_piece(next,&out,p)){free(next);return false;}}else{size_t left=pos>ps?pos-ps:0;size_t right=pe>end?pe-end:0;if(left&&!append_piece(next,&out,(Piece){p.source,p.start,left})){free(next);return false;}if(right&&!append_piece(next,&out,(Piece){p.source,p.start+p.length-right,right})){free(next);return false;}}logical=pe;}free(t->pieces);t->pieces=next;t->piece_count=out;t->size-=len;return true;}
static const uint8_t*source_ptr(const PieceTable*t,const Piece*p){return p->source==SRC_ORIGINAL?t->original:t->add;}
bool piece_table_get(const PieceTable*t,size_t idx,uint8_t*out){if(!t||!out||idx>=t->size)return false;size_t logical=0;for(size_t i=0;i<t->piece_count;++i){Piece p=t->pieces[i];if(idx-logical<p.length){*out=source_ptr(t,&p)[p.start+(idx-logical)];return true;}logical+=p.length;}return false;}
bool piece_table_copy(const PieceTable*t,uint8_t*out,size_t cap){if(!t)return false;if(t->size>0&&!out)return false;if(cap<t->size)return false;size_t off=0;for(size_t i=0;i<t->piece_count;++i){Piece p=t->pieces[i];memcpy(out+off,source_ptr(t,&p)+p.start,p.length);off+=p.length;}return off==t->size;}
bool piece_table_validate(const PieceTable*t){if(!t)return false;if(t->original_size>0&&!t->original)return false;if(t->add_size>t->add_capacity||(t->add_capacity>0&&!t->add))return false;if(t->piece_count>0&&!t->pieces)return false;size_t total=0;for(size_t i=0;i<t->piece_count;++i){Piece p=t->pieces[i];if(p.length==0)return false;size_t limit=p.source==SRC_ORIGINAL?t->original_size:(p.source==SRC_ADD?t->add_size:0);if(p.source!=SRC_ORIGINAL&&p.source!=SRC_ADD)return false;if(p.start>limit||p.length>limit-p.start)return false;if(SIZE_MAX-total<p.length)return false;total+=p.length;if(i>0){Piece q=t->pieces[i-1];if(q.source==p.source&&q.start+q.length==p.start)return false;}}return total==t->size;}
